version: "3"
services:
  reverse-proxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy
  udagram-backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  udagram-backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend