version: 2.1

executors:
  docker-executor:
    docker:
      - image: udagram-backend-feed
      - image: udagram-backend-user
      - image: udagram-frontend
      - image: reverse-proxy

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Checkout your source code
      
      - setup_remote_docker:
          version: default  # Use a specific version of Docker
          docker_layer_caching: true  # Optional: speeds up Docker builds

      # Optional: Push Docker image to a Docker registry
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml build --parallel
            docker-compose -f docker-compose-build.yaml push

workflows:
  version: 2
  build_and_test:
    jobs:
      - build