version: 2.1

jobs:
  Refactor-monolith-to-microservices:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for microservices
          command:
            curl -fsSL https://dep.nodesource.com/setup_16.x | sudo -E bash - 
            sudo apt-get install -y nodejs
            node -v
            npm -v

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed haqh310/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user haqh310/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend haqh310/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxyr
            docker tag udagram-reverseproxy haqh310/udagram-reverseproxy:v1

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            docker push haqh310/udagram-api-feed:v1
            docker push haqh310/udagram-api-user:v1
            docker push haqh310/udagram-frontend:v1
            docker push haqh310/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - Refactor-monolith-to-microservices
      - build-docker:
          requires: [Refactor-monolith-to-microservices]





executors:
  docker-executor:
    docker:
      - image: udagram-backend-feed
      - image: udagram-backend-user
      - image: udagram-frontend
      - image: reverse-proxy

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Checkout your source code
      
      - setup_remote_docker:
          version: default  # Use a specific version of Docker
          docker_layer_caching: true  # Optional: speeds up Docker builds

      # Optional: Push Docker image to a Docker registry
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml build --parallel
            docker-compose -f docker-compose-build.yaml push

workflows:
  version: 2
  build_and_test:
    jobs:
      - build