apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend   
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend    
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
    spec:
      containers:
      - image: haqh310/udagram-frontend:v1
        name: udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"


